version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: salon
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data

volumes:
  postgres_database: